---
title: "Salt lines supplemental"
author: Ahmed Hasan
output: pdf_document
---

# Package import

```{r}
library(tidyverse)
library(here)
library(fs)
library(wesanderson)
```

# Tables

## Table S1 - HS mutations

```{r}
adaptation = read_tsv(
  here('data/rate/mut_describer/adaptation.gene_sets.filtered.tsv'),
  col_types = cols(), na = c('.')
) %>% 
  select(
    chromosome, position, mutation, type, mutant_sample,
    gene = Gene.primaryIdentifier, is_salt_gene = perrineau,
    genic:CDS
  )

write_tsv(adaptation, file = here('data/supplemental/table_s1.tsv'))
```

## Table S2 - Salt MA mutations

```{r}
salt_ma = read_tsv(
  here('data/rate/mut_describer/muts_described.final.gene_sets.tsv'),
  col_types = cols()
) %>% 
  mutate(rho = as.double(rho)) %>% 
  bind_rows(
    read_tsv(
      here('data/rate/mut_describer/indels_described.gene_sets.tsv'),
      col_types = cols()
    ) %>% 
      mutate(mut_codon = as.character(mut_codon)) # needed for join
  ) %>% 
  mutate(
    sample_group = str_extract(mutant_sample, '^[A-Z]{2}'),
    sample_type = str_extract(mutant_sample, '[05]$'),
    sample_factor = paste(sample_group, sample_type, sep = '_')
  ) %>% 
  filter(sample_type == '5') %>% 
   mutate(
    gene = str_match(feature_names, "^\\[\\'([A-Za-z\\.0-9]+)")[, 2] # lol
  ) %>% 
  select(
    chromosome, position, mutation, type, mutant_sample,
    gene, is_salt_gene = perrineau, genic:CDS
  )

write_tsv(salt_ma, file = here('data/supplemental/table_s2.tsv'))

```

# Figures

## Figure S1 - annotations within Salt MA

Data generated in `annotation.Rmd` - loading in:

```{r}
salt_ma_spatial = read_tsv(
  here('data/spatial/salt_ma_annotations_cis.tsv'),
  col_types = cols()
) %>% 
  select(sample_factor, ant = annotation, prop, contains('ci')) %>% 
  mutate(gene_set = 'genome wide') %>% 
  filter(str_extract(sample_factor, '[05]$') == 5) %>% 
  mutate(
    sample_factor = case_when(
      sample_factor == 'CC_5' ~ 'original MA strains',
      sample_factor == 'DL_5' ~ 'HS line ancestors',
      sample_factor == 'SL_5' ~ 'salt tolerant lines'
    )
  )

salt_ma_spatial_perrineau = read_tsv(
  here('data/supplemental/salt_ma_perrineau.tsv'),
  col_types = cols()
) %>% 
  mutate(gene_set = 'candidate salt genes') %>% 
  filter(!is.na(prop)) %>% 
  filter(str_extract(sample_factor, '[05]$') == 5) %>% 
  mutate(
    sample_factor = case_when(
      sample_factor == 'CC_5' ~ 'original MA strains',
      sample_factor == 'DL_5' ~ 'HS line ancestors',
      sample_factor == 'SL_5' ~ 'salt tolerant lines'
    )
  )
```

Plot (code from `annotation.Rmd`)

```{r}
palette = wes_palette('Darjeeling1', 5)

fig_s1 = salt_ma_spatial %>% 
  bind_rows(salt_ma_spatial_perrineau) %>% 
  # set up data
  mutate(sample_factor = ifelse(sample_factor == 'Salt MA (salt)', 'Salt MA', sample_factor),
         gene_set = ifelse(gene_set == 'salt genes', 'candidate salt genes', gene_set)) %>% 
  mutate(
    ant = case_when(
      ant == 'utr5' ~ "5' UTR",
      ant == 'utr3' ~ "3' UTR",
      TRUE ~ as.character(ant)
    )
  ) %>% 
  mutate(
    sample_factor = fct_relevel(sample_factor, 
      c('original MA strains', 'HS line ancestors', 'salt tolerant lines')),
    gene_set = fct_relevel(
      gene_set, c('genome wide', 'candidate salt genes')),
    ant = fct_relevel(
      ant, c('intergenic', "5' UTR", 'CDS', 'intronic', "3' UTR")
    )
  ) %>% 

  # plot
  ggplot(
    aes(x = ant, y = prop, fill = sample_factor)) +
  geom_bar(
    stat = 'identity', 
    position = position_dodge(width = 0.9),
    colour = 'black',
    size = 0.4) +
  geom_errorbar(
    aes(ymin = lower_ci, ymax = upper_ci),
    position = position_dodge(width = 0.9),
    size = 0.4, width = 0.2
  ) +
  facet_grid(
    ~ gene_set, scales = 'free') +
  coord_cartesian(
    y = c(0, 1)
  ) +
  labs(
    x = '',
    y = 'Proportion of all mutations'
  ) +
  scale_fill_manual(
    values = c(
      'original MA strains' = palette[1], # '#87C5FC', orig color
      'HS line ancestors' = palette[3], # '#FF5B5F', orig color
      # 'Salt MA (control)' = palette[6], 
      'salt tolerant lines' = palette[5])
  ) +
  # macro elements
  guides(fill = guide_legend(
    override.aes = list(color = 'white'))
  ) +
  theme(
    panel.border = element_rect(colour = 'black', size = 0.5, fill = NA),
    panel.background = element_blank(),
    strip.background = element_blank(),
    legend.position = c(0.175, 0.8),
    legend.text = element_text(size = 8, colour = 'black'),
    legend.title = element_blank(),
    legend.key = element_rect(color = 'white'),
    legend.key.size = unit(0.5, 'cm')) +
  # text elements
  theme(
    strip.text = element_text(family = 'Helvetica', colour = 'black', size = 10),
    axis.title = element_text(family = 'Helvetica', colour = 'black', size = 10),
    axis.text = element_text(family = 'Helvetica', colour = 'black', size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

fig_s1

ggsave(here('plots/fig_s1.eps'), plot = fig_s1, width = 6, height = 4)
```

## Figure S2 - Ka/Ks across salt MA groups